#!/usr/bin/env bash
source client.in
REPO_NAME="$1"
if [ ! $REPO_NAME ]; then
    echo "Usage: $0 repo_name"
    exit
fi

# check for git version here, 2.4 works. Add ppa if this version is not
# avaialble on system.
source server.in
# Cool, now everything is setup, create a empty repo on server.
if $SSH $SERVER_URL server_init $REPO_NAME 
then
    echo "Created $REPO_NAME successfully on server"
    echo "You can clone it using bhandar_clone script"
else
    echo "Could not create $REPO_NAME on server"
    exit 1
fi
