#!/usr/bin/env bash
GIT_VERSION=`git --version`
if [ ! `which sshpass` ]; then
    echo "Install sshpass utility"
    exit
fi

REPO_NAME="$1"
if [ ! $REPO_NAME ]; then
    echo "Usage: $0 repo_name"
    exit
fi

# check for git version here, 2.4 works. Add ppa if this version is not
# avaialble on system.
SCRIPTDIR='.'
source $SCRIPTDIR/bhandar.env
source $SCRIPTDIR/bhandar_ssh.in

SSH="sshpass -e ssh"

# Cool, now everything is setup, create a empty repo on server.
$SSH $SHARE_USER@$SHARE_HOST '$HOME/data_over_git_ssh/server_init' $REPO_NAME
