#!/bin/bash
source server.in
declare -i i
i=0
echo "Repositories are on server"
for d in `ls $SERVER_REPO_ROOT` ; do
	i=$((i + 1))
	objects=`cd $SERVER_REPO_ROOT/$d; git count-objects`
	printf "%-20s %0s\n" "$i. $d" "$objects" 
done
