#!/bin/bash
# THis is server side script. Should not be executed on host.
source bhandar.env
REPONAME="$1"
if [[ "$REPONAME" ]]; then
	REPOPATH=$HOME/repositories/$REPONAME
	mkdir -p $REPOPATH
	( cd $REPOPATH && git init --bare )
	echo "Created bare repo at $REPOPATH"
else
	echo "Invalid repo name $REPOPATH"
fi
